version: "3"

vars:
  SHELL: bash

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list

  fmt:
    desc: Format code with rustfmt
    cmds:
      - cargo fmt

  fmt:check:
    desc: Check if code is formatted (CI-friendly)
    cmds:
      - cargo fmt -- --check

  lint:
    desc: Run clippy linter
    cmds:
      - cargo clippy -- -D warnings

  build:
    desc: Build the project (default, without feature)
    deps: [fmt, lint]
    cmds:
      - cargo build

  build:print-42:
    desc: Build with print-42 feature enabled
    deps: [fmt, lint]
    cmds:
      - cargo build --features print-42

  build:lucky-number:
    desc: Build with lucky-number feature enabled
    deps: [fmt, lint]
    cmds:
      - cargo build --features lucky-number

  build:all-features:
    desc: Build with all features enabled
    deps: [fmt, lint]
    cmds:
      - cargo build --all-features

  run:
    desc: Run the program (default output)
    deps: [build]
    cmds:
      - cargo run

  run:print-42:
    desc: Run the program with print-42 feature enabled
    deps: [build:print-42]
    cmds:
      - cargo run --features print-42

  run:lucky-number:
    desc: Run the program with lucky-number feature enabled
    deps: [build:lucky-number]
    cmds:
      - cargo run --features lucky-number

  run:all-features:
    desc: Run the program with all features enabled
    deps: [build:all-features]
    cmds:
      - cargo run --all-features

  run:minimal:
    desc: Run the program with no default features (opt-out)
    cmds:
      - cargo run --no-default-features

  check:minimal:
    desc: Quick compile check with no default features (opt-out)
    cmds:
      - cargo check --no-default-features

  test:
    desc: Run all tests
    cmds:
      - cargo test

  check:
    desc: Quick compile check without building
    cmds:
      - cargo check

  check:print-42:
    desc: Quick compile check with print-42 feature enabled
    cmds:
      - cargo check --features print-42

  check:lucky-number:
    desc: Quick compile check with lucky-number feature enabled
    cmds:
      - cargo check --features lucky-number

  check:all-features:
    desc: Quick compile check with all features enabled
    cmds:
      - cargo check --all-features

  clean:
    desc: Clean build artifacts
    cmds:
      - cargo clean
